### ISSUE TITLE
create list of Florida Legislators with their ccid

### ISSUE THREAD

**Issue by shelbygreen** [shelbygreen/florida-legislature#7]
legislator's name, district, party, role, ccid, [vote on SB 300](https://www.myfloridahouse.gov/Sections/Bills/floorvote.aspx?VoteId=21764&BillId=78468&SessionId=99&) (hearing was today, 4/3/23)

ccid formula: 12 + 000 (number of district) + U (for Senate)

example - ccid: 12030U

**Comment by TheNextCEO** [comment]
[SB 300 - data - Sheet1.csv](https://github.com/shelbygreen/florida-legislature/files/11142904/SB.300.-.data.-.Sheet1.csv)

**Comment by shelbygreen** [comment]
thank you kind sir

**Comment by shelbygreen** [comment]
can you add first name and last name fields?

**Comment by shelbygreen** [comment]
Senator Torres abstained from voting. So it would be "na" instead of "m"

**Comment by TheNextCEO** [comment]
[SB 300 - data - Sheet1.csv](https://github.com/shelbygreen/florida-legislature/files/11151257/SB.300.-.data.-.Sheet1.csv)

**Comment by TheNextCEO** [comment]
[SB 300 - data - Sheet1.csv](https://github.com/shelbygreen/florida-legislature/files/11152016/SB.300.-.data.-.Sheet1.csv)

**Comment by shelbygreen** [comment]
thank you this works!
